<div class="explanation">
<p>Google+ では、＋１をしてくれた人が最大でも50人までしか表示されませんが、その制限を回避して全員を表示させるためのアプリです。</p>
<p>ログインして Google+ と接続すると自分の投稿した記事(自分だけの記事は出てきません)が一覧されますので、＋１してくれた人を調べたい記事をクリックしてください。</p>
<p>＋１してくれた方のアイコンと表示名が表示されますので、クリックして＋１してくれた方のプロフィールを参照してください。</p>
<p>現段階では、パソコンブラウザにしか対応してません。あしからずご了承くださいませ。</p>
<p>不具合報告、文句その他もろもろは、<a href="https://plus.google.com/110879878982258227165/" alt="HOSOKAWA Tetsuichi">HOSOKAWA Tetsuichi</a> までどうぞ。</p>
<p>デザインセンスゼロの人間が作ってるので、見た目なんとかしてやろうとか、パーツの配置をこうしたほうが良いとか言うのも歓迎です。</p>
</div>
<div id="disconnect-button"><button onclick="disconnectUser()">このアプリをG+から接続解除</button></div>
<div id="reset-button"><button onclick="location.href='http://www.dear-jpn.com/google-plus/'">リセット</button></div>
<div id="information-area"></div><div id="result-area"></div>
<div id="posts">
<div id="post-block"></div>
<div id="posts-top"><button onclick="listPosts(null)">投稿先頭</button></div>
<div id="posts-next"></div>
</div>
<div id="plusone">
<div id="plusone-post-block"></div>
<div id="plusone-block"></div>
<div id="plusone-top"></div>
<div id="plusone-next"></div>
</div>
%%login-button%%
%%google-plus-script%%
