<script type="text/javascript">
var access_token = "";
var maxAnalyzePosts = <?php echo $this->config('APPLICATION.MAX_ANALYZE_POST') ?>;
var plusOneInfo = {
    collecting: true,
    postIndex: 0,
    onerPageToken: undefined,
    activities: undefined,
    plusOner: {}
};
var circleObj = {};
var listPostCount = <?php echo $this->config('APPLICATION.LIST_POST_COUNT') ?>;
var listPlusOneCount = <?php echo $this->config('APPLICATION.LIST_PLUS_ONE_COUNT') ?>;
</script>
