<span id="signinButton" style="display: none">
  <span
    class="g-signin"
    data-callback="signinCallback"
    data-clientid="<?php echo $this->config('GOOGLEPLUS_API.CLIENT_ID') ?>"
    data-cookiepolicy="single_host_origin"
    data-requestvisibleactions="http://schemas.google.com/AddActivity"
    data-scope="https://www.googleapis.com/auth/plus.login">
  </span>
</span>
<script type="text/javascript">
if (!access_token) {
    document.getElementById('signinButton').setAttribute('style', 'display: inline');
}
</script>
